# Generated by Django 3.2.4 on 2021-06-16 19:32

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
                'ordering': ['id'],
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Depatamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_postal', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Codigo postal')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['departamento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False, verbose_name='Verificacion')),
                ('aceptado', models.BooleanField(verbose_name='Aceptada')),
            ],
            options={
                'verbose_name': 'Verificacion',
                'verbose_name_plural': 'Verficaciones',
                'db_table': 'verificacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='DUI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('sexo', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro')], max_length=15, verbose_name='Sexo')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.departamento', verbose_name='Departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='SubsidioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_subsidio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Subsidio')),
                ('cantidad_buses', models.IntegerField(verbose_name='Cantidad buses')),
                ('cantidad_microbuses', models.IntegerField(verbose_name='Cantidad microbuses')),
                ('frecuencia_uso', models.CharField(choices=[('diaramente', 'Diaramente'), ('semanalmente', 'Semanalmente'), ('mensualmente', 'Mensualmente')], max_length=50, verbose_name='Frecuencia uso')),
                ('pertenece', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario', verbose_name='Benefeciario')),
            ],
            options={
                'verbose_name': 'Subsidio transporte',
                'verbose_name_plural': 'Subsidios transporte',
                'db_table': 'subsidio_transporte',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubsidioLuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_subsidio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad subsidioTransporte')),
                ('cantidad_consumo', models.DecimalField(decimal_places=2, help_text='cantidad de consumo en kilowatts por hora', max_digits=10, verbose_name='Cantidad consumida')),
                ('recibo_luz', models.ImageField(null=True, upload_to='recibos/recibosLuz')),
                ('pertenece', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario', verbose_name='Benefeciario')),
            ],
            options={
                'verbose_name': 'Subsidio luz',
                'verbose_name_plural': 'Subsidios luz',
                'db_table': 'subsidio_luz',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubsidioGasLicuado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_subsidio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad subsidioTransporte')),
                ('cantidad_consumo', models.DecimalField(decimal_places=2, help_text='cantidad de consumo en kilowatts por hora', max_digits=10, verbose_name='Cantidad consumida')),
                ('tipo_establecimiento', models.CharField(choices=[('Hogar familiar', 'Hogar'), ('Negocio subsistencia', (('tortilleria', 'Tortilleria'), ('pupuseria', 'Pupuseria'), ('panaderia', 'Panaderia')))], max_length=50, verbose_name='Tipo beneficiario')),
                ('num_tarjeta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero tarjeta')),
                ('recibo_luz', models.ImageField(null=True, upload_to='recibos/recibosGas')),
                ('pertenece', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario', verbose_name='Benefeciario')),
            ],
            options={
                'verbose_name': 'Subsidio gas licuado',
                'verbose_name_plural': 'Subsidios gas licuado',
                'db_table': 'subsidio_gas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubsidioAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_subsidio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad subsidioTransporte')),
                ('cantidad_consumo', models.DecimalField(decimal_places=2, help_text='cantidad de consumo en metros cubicos', max_digits=10, verbose_name='Cantidad consumida')),
                ('recibo_agua', models.ImageField(null=True, upload_to='recibos/recibosAgua')),
                ('pertenece', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario', verbose_name='Benefeciario')),
            ],
            options={
                'verbose_name': 'Subsidio agua',
                'verbose_name_plural': 'Subsidios agua',
                'db_table': 'subsidio_agua',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.verificacion')),
                ('pertenece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario')),
                ('subsidio_agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.subsidioagua')),
                ('subsidio_gas_licuado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.subsidiogaslicuado')),
                ('subsidio_luz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.subsidioluz')),
                ('subsidio_transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.subsidiotransporte')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
    ]
