# Generated by Django 3.2.4 on 2021-06-17 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario', unique=True),
        ),
    ]
