# Generated by Django 3.2.4 on 2021-06-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_solicitud_pertenece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='pertenece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.usuario'),
        ),
    ]
