# Generated by Django 3.2.4 on 2021-06-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210623_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidioagua',
            name='cantidad_subsidio',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad subsidiada'),
        ),
        migrations.AlterField(
            model_name='subsidioagua',
            name='recibo_agua',
            field=models.ImageField(null=True, upload_to='recibosAgua/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subsidiogaslicuado',
            name='num_tarjeta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero tarjeta'),
        ),
        migrations.AlterField(
            model_name='subsidiogaslicuado',
            name='recibo_luz',
            field=models.ImageField(null=True, upload_to='recibosGas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subsidioluz',
            name='recibo_luz',
            field=models.ImageField(null=True, upload_to='recibosLuz/%Y/%m/%d/'),
        ),
    ]
