# Generated by Django 3.2.4 on 2021-06-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_subsidioagua_cantidad_subsidio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidioagua',
            name='cantidad_consumo',
            field=models.FloatField(help_text='cantidad de consumo en metros cubicos', verbose_name='Cantidad consumida'),
        ),
        migrations.AlterField(
            model_name='subsidioagua',
            name='cantidad_subsidio',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad subsidiada'),
        ),
        migrations.AlterField(
            model_name='subsidiogaslicuado',
            name='tipo_establecimiento',
            field=models.CharField(choices=[('Hogar familiar', 'Hogar'), ('Negocio subsistencia', (('tortilleria', 'Tortillería'), ('pupuseria', 'Pupusería'), ('panaderia', 'Panadería')))], max_length=50, verbose_name='Tipo beneficiario'),
        ),
    ]
