# Generated by Django 3.2.4 on 2021-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20210626_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidioagua',
            name='verificacion',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
