# Generated by Django 3.2.4 on 2021-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_subsidioagua_verificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidioagua',
            old_name='verificacion',
            new_name='verificado',
        ),
        migrations.AddField(
            model_name='subsidioagua',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobación'),
        ),
    ]
