# Generated by Django 3.2.4 on 2021-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20210626_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidioluz',
            name='cantidad_subsidio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad subsidiada'),
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.DeleteModel(
            name='Verificacion',
        ),
    ]
